safe: true
permalink: pretty
baseurl: /
markdown: kramdown

# Website title
title: Corinna Jentzsch

# Default meta description and keywords
description: Corinna Jentzsch's homepage
keywords: 
  - 'keyword 1'
  - 'keyword 2'
  - 'keyword 3'
  - 'who really cares about keywords' 

navigation:
- text: Research
  url: /research/
- text: Teaching
  url: /teaching/
- text: CV
  url: /cv/

# Files to exclude from build
exclude: ['README.md']

prose:
  siteurl: 'http://coboje.github.io/'
  media: 'assets/media'
  metadata:
    - name: 'layout'
      field:
        element: 'multiselect'
        label: 'Select Layout'
        placeholder: 'Choose Layout'
        options:
          - name: 'No Sidebar'
            value: default
          - name: 'With Sidebar'
            value: sidebar

