safe: true
permalink: pretty
baseurl: /
markdown: kramdown

kramdown: 
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  auto_ids: true

# Website title
title: Corinna Jentzsch

# Default meta description and keywords
description: Corinna Jentzsch's website
keywords: 
  - 'African Politics'
  - 'political science'
  - 'Mozambique'
  - 'civil war'
  - 'militias'
  - 'contemporary political theory'
  - 'contemporary political theory'  

navigation:
- text: Research
  url: /research/
- text: Teaching
  url: /teaching/
- text: CV
  url: /cv/

# Files to exclude from build
exclude: ['README.md']

prose:
  siteurl: 'http://coboje.github.io/'
  rooturl: .
  media: 'assets/media'
  metadata:
    .:
      - name: 'layout'
        field:
          element: 'multiselect'
          label: 'Select Layout'
          placeholder: 'Choose Layout'
          options:
            - name: 'No Sidebar'
              value: default
            - name: 'With Sidebar'
              value: sidebar
  
